version: '3'
services:
  app:
    build: ./
    ports:
      - "3004:3004"
    expose:
      - 3004
    volumes:
      - ./:/app
      - /app/node_modules
    container_name: react-skeleton
    env_file:
      - ./.env